name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Gradle Wrapper 무결성 검사(보안상 강추)
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'       # 프로젝트 JDK 버전에 맞추세요(17 또는 21 권장)
          distribution: 'temurin'
          cache: 'gradle'          # 의존성 캐시로 속도↑

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew clean build --no-daemon

      # 실패 원인 파악용 리포트 업로드(선택)
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/test
            build/test-results/test

